version: "3.9"
services:
  # MySQL
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: rumah_sakit

  adminer:
    image: adminer
    restart: always
    ports:
      - 9191:8080

  app:
    container_name: api_rumah_sakit
    build: .
    restart: always
    ports:
      - 8001:8001
    volumes:
      - .:/usr/src/app/
